module.exports = {
  OPEN_LOG_FORM: "OPEN_LOG_FORM",
  CLOSE_LOG_FORM: "CLOSE_LOG_FORM",
  OPEN_EDIT_FORM: "OPEN_EDIT_FORM",
  CLOSE_EDIT_FORM: "CLOSE_EDIT_FORM",
  PATIENT_UPDATED: "PATIENT_UPDATED",
  LOG_ERROR: "LOG_ERROR",
  LOG_EDIT_ERROR: "LOG_EDIT_ERROR"
};
